### PR TITLE
Rm unused files

### PR DESCRIPTION
**Pull request by mikebentley15**
- I think there are many unused files in the repository.  This is an attempt to remove them to clean it up a bit.
- Please check the list of files.  I don't want to delete needed files.
- Also check what's left.  I want to be sure to delete all unnecessary files to keep the code base clean.
- I had to wait until the directory renaming was merged in before doing this pull request since it had merge conflicts with that other change.
- I also removed the qfpc/Makefile directory and renamed qfpc/Makefile2 -> qfpc/Makefile.

Thanks :smile:

### CODE REVIEW

**Comment by Geof23** [comment]
Michael, there are several in this list I want.  I'll get to it later.

**Comment by mikebentley15** [comment]
Understandable.  I just guessed based on what is necessary to run QFPC and
QFPD.  We can cancel this pull request, or you can let me know which files
you still want to keep.

Thanks,
Mike

**Comment by Geof23** [comment]
Cool -- Ok, here's a list 'to keep':


   - *D* db/psql_commands/create_cleanupResults
   <https://github.com/Geof23/QFP/pull/17/files#diff-5> (22)
   - *D* db/psql_commands/create_importQFPResults
   <https://github.com/Geof23/QFP/pull/17/files#diff-7> (17)
   - *D* db/psql_commands/create_import_switches.py
   <https://github.com/Geof23/QFP/pull/17/files#diff-9> (17)
   - *D* db/psql_commands/import_test
   <https://github.com/Geof23/QFP/pull/17/files#diff-11> (1)
   -
- *M* qfpc/Makefile <https://github.com/Geof23/QFP/pull/17/files#diff-13>
   (162)
   - *D* qfpc/Makefile2
   <https://github.com/Geof23/QFP/pull/17/files#diff-14> (91)

So do I interpret this correctly to assume that you're replacing Makefile2
with Makefile?  This is cool as long as you updated the references to it
(which you probably did).

Fine, we can rely on history for MIC junk.

BTW, I'm going to add an easy test to run before making pull requests --
just a run of Makefile(2) with a diff on output against a historical
version.

Thanks for your effort

**Comment by mikebentley15** [comment]
Is that good?

And yes, I deleted Makefile and renamed Makefile2 as Makefile.  I did go
through and change all references in the second commit.  If you look at the
second commit in isolation, it shows how I replaced the Makefile.

Thanks,
Mike

**Comment by Geof23** [comment]
sounds good!

**Pull request merged**
