### PR TITLE
Issue 011

### PR DESCRIPTION
**Pull request by mikebentley15**
* Fixed all warnings (from -Wall and -Wextra)
* Removed functions projectType() and replaced usage with reinterpret functions
* Add zeroing out the top bits of long double -> unsigned __int128 to the reinterpret functions
* Place reinterpret functions at the top of the namespace so they can be used.  This was chosen instead of forward declaring the template functions, because forward declaring templates is hard :)

### CODE REVIEW

**Comment by Geof23** [comment]
It looks good -- thanks.

Did you test?

**Comment by mikebentley15** [comment]
I ran it on my box with MakefileDev.  Everything compiles and all warnings
are gone :)

- Mike

**Comment by Geof23** [comment]
>
> I ran it on my box with MakefileDev. Everything compiles and all warnings
> are gone :)
>

Great -- thanks again

BTW, I think you broke 'Makefile2'.  I think I found the problem though --
a single '$' accidentally got erased!

'make' autocomplete is a lifesaver -- i.e. 'make -f Makefile2 [tab] [tab]'

**Comment by mikebentley15** [comment]
Aw man, I was afraid of that.  Today I will get comfortable with testing
with Makefile2.  Thanks for fixing it!

**Comment by Geof23** [comment]
It happens.  I haven't fixed it but will push today

**Comment by Geof23** [comment]
Michael, I fixed this issue on rel_lt.

From your dev branch, you can do:

git checkout rel_lt -- perpVects/Makefile2

**Comment by mikebentley15** [comment]
Will do, thanks!

**Pull request merged**
